### ISSUE TITLE
Mailinabox installation Z-push checksum issue

### ISSUE THREAD

**Issue by mahanmp** [mail-in-a-box/mailinabox#1307]
I got a sort of a problem with Z-push package 

<img width="702" alt="zpush" src="https://user-images.githubusercontent.com/1390979/34325319-17b0fe16-e8c9-11e7-90f6-3076f6d0ed7a.png">

the z-push package is giving a different checksum against the expected checksum of miab, how can we fix this issue? :)

**Comment by dannyvankooten** [comment]
I ran into exactly this just now as well.

**Comment by dannyvankooten** [comment]
Looks like this is fixed in `master` already, a0e603a3c6a802364b61a974f6a21c0612ccb5cb

**Comment by hachre** [comment]
This has already been fixed, see:
https://github.com/mail-in-a-box/mailinabox/issues/1304

**Comment by mahanmp** [comment]
I am rerunning the whole installation process i still face the same issue, any ways to fix the issue?

**Comment by mahanmp** [comment]
Ok i got it working now thank you
