### ISSUE TITLE
ubuntu_bionic resolv.conf doesnt point dns to 127.0.0.1 due to systemd-resolved

### ISSUE THREAD

**Issue by jvolkenant** [mail-in-a-box/mailinabox#1424]
https://github.com/mail-in-a-box/mailinabox/blob/ccc276903d3ce5b5eee91607e71243c0a746dbc2/setup/system.sh#L290

Bionic now uses systemd-resolved for dns managing resolv.conf.  Might need to rip it out or find a way to have resolvconf work with it.

**Comment by JoshData** [comment]
Interesting. Thanks for noting that.

According to https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html, systemd-resolved handles DNSSEC, which is the only reason we were installing bind9. (DNSSEC is needed for DANE for outbound mail.) So it seems like we may be able to simply remove bind9 from Mail-in-a-Box.

**Comment by JoshData** [comment]
Ah, er, maybe not. Since it's a "stub" resolver, I think that means it relies on upstream servers to do recursive/DNSSEC lookups and it just reports the results.

**Comment by JoshData** [comment]
I actually just pushed a commit to `ubuntu_bionic` that goes the other way. It looks like we can do this by enabling local DNSSEC validation in systemd-resolved and dropping bind9 entirely.

**Comment by JoshData** [comment]
Here's the commit: https://github.com/mail-in-a-box/mailinabox/commit/01636fbb55bc6fcf74a7c51a4c33e2e43d5820e8

If I got it right in that commit, we can close this issue I think.

**Comment by just4t** [comment]
> I actually just pushed a commit to `ubuntu_bionic` that goes the other way. It looks like we can do this by enabling local DNSSEC validation in systemd-resolved and dropping bind9 entirely.

@JoshData Noticed not ALL cloud servers providers provide the same Ubuntu 18.04 ready image then when one just fail setting the _/etc/hosts_ and /_etc/hostname_ as needed (DigitalOcean) and the rest of the process works correctly, other(s) fail because not all the needed packages are being provided by default: 

- See the >VULTR install attempt that fails because 'virtualenv' and some (or many) 'python' pakages are not found by default. Please, pay a look to the following [**CAST**](https://asciinema.org/a/RhB6Myd98sGRLZTRAY0gE8WCX) to see the full installation process (including mentioned errors). Hope this helps to debug it!

**Note: this test server will be deleted after having tested if DNSSEG validates correctly at the admin panel or not yet** (I'll post again about here if still fails).

**Comment by just4t** [comment]
But still doesn't point dns to 127.0.0.1 as expected by default (DigitalOcean & VULTR so far) then needed to manually edit the _/etc/hosts_ file by changing:

from:
`127.0.0.1 box.mydomain.tld`

to:
`127.0.0.1 guest`
`<SERVER-EXTERNAL_IP_ADDRESS>  box.mydomain.tld`

To have it working correctly and green reported at the admin panel.

> How to make it to work correctly without needing to edit the _/etc/hosts_ file?

**Comment by jvolkenant** [comment]
I did a fresh install of 18.04 and the ubuntu_bionic branch, the install completes however since we don't have bind9, dns requests are being forwarded upstream intead of being done directly.  This breaks urlbl.com lookups and spamhaus lookups (and pretty much all other rbl lookups)

During the install, I chose 4.2.2.2 as my dns server (typically is replaced with 127.0.0.1 using bind9 during mailinabox install)

/etc/resolv.conf is updated to 127.0.0.53, but requests are still forwarded to 4.2.2.2:

root@m:~/mailinabox# systemd-resolve --status
Global
          DNSSEC NTA: 10.in-addr.arpa
                      16.172.in-addr.arpa
                      168.192.in-addr.arpa
                      17.172.in-addr.arpa
                      18.172.in-addr.arpa
                      19.172.in-addr.arpa
                      20.172.in-addr.arpa
                      21.172.in-addr.arpa
                      22.172.in-addr.arpa
                      23.172.in-addr.arpa
                      24.172.in-addr.arpa
                      25.172.in-addr.arpa
                      26.172.in-addr.arpa
                      27.172.in-addr.arpa
                      28.172.in-addr.arpa
                      29.172.in-addr.arpa
                      30.172.in-addr.arpa
                      31.172.in-addr.arpa
                      corp
                      d.f.ip6.arpa
                      home
                      internal
                      intranet
                      lan
                      local
                      private
                      test

Link 2 (ens18)
      Current Scopes: DNS
       LLMNR setting: yes
MulticastDNS setting: no
      DNSSEC setting: yes
    DNSSEC supported: yes
         DNS Servers: 4.2.2.2
          DNS Domain: localdomain



Testing URLBL:
http://uribl.com/refused.shtml
14.04:
root@m:~# host -tTXT 2.0.0.127.multi.uribl.com
2.0.0.127.multi.uribl.com descriptive text "permanent testpoint"

18.04 ubuntu_bionic:

root@m:~/mailinabox# host -tTXT 2.0.0.127.multi.uribl.com
2.0.0.127.multi.uribl.com descriptive text "127.0.0.1 -> Query Refused. See http://uribl.com/refused.shtml for more information [Your DNS IP: 8.0.22.8]"


Testing spamhaus:

14.04:
root@m:~# dig +short 2.0.0.127.zen.spamhaus.org                     
127.0.0.4
127.0.0.10
127.0.0.2

18.04:
root@m:~/mailinabox# dig +short 2.0.0.127.zen.spamhaus.org


In the two above examples, 14.04 install works properly, 18.04 is forwarding to another dns server.  Should be doing lookups directly from mailinabox hosts.

**Comment by JoshData** [comment]
>  This breaks urlbl.com lookups and spamhaus lookups (and pretty much all other rbl lookups)

Yikes. Nice catch. That's really annoying because using the default system resolver lets us simplify Mail-in-a-Box. So I guess I'll revert the change and we'll disable systemd-resolved.

**Comment by jvolkenant** [comment]
https://www.ctrl.blog/entry/resolvconf-tutorial has some info on dealing with systemd-resolved.  I still need to test what way would be best to get back to the old way of handling /etc/resolv.conf.  I feel like RESOLVCONF=yes didn't take over handling resolv.conf, unless it was preempted by systemd-resolved

**Comment by JoshData** [comment]
I removed the commit with systemd-resolved changes from the ubuntu_bionic branch and I pushed some simple updates to the bind9 setup, and so far it's working for me.

**Comment by JoshData** [comment]
I upgraded my personal Mail-in-a-Box to the ubuntu_bionic branch and things seem to be working smoothly, so I am going to close this issue. Thanks all for helping to figure it out!

**Comment by just4t** [comment]
> 
> 
> I upgraded my personal Mail-in-a-Box to the ubuntu_bionic branch and things seem to be working smoothly, so I am going to close this issue. Thanks all for helping to figure it out!

@JoshData Installed now 181007-1953 CEST the _ubuntu_bionic_ branch as fresh, over a VULTR 18.04 image and still reported issues remain at _installing mailinabox daemon_ because the VULTR provided image doesn't built by default the _virtualenv_ and some or all of the following _python_ packages (I can't identify which ones are already in or not) then needed to install those packages to make the installation to end smoothly:
`apt-get install virtualenv`
`apt-get install python3 python-dev python3-dev`
`apt-get install build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev`
`apt-get install python-pip`
`apt-get install python-all-dev python-setuptools python-wheel`

- I think you should include them to be checked and if not in to call them to be installed, within the script if not we will get lots of support calls about, when not using _DigitalOcean_ alike CLOUD server providers.

Hope this helps.

**Comment by JoshData** [comment]
Open a new issue? That doesn't seem to be related to the original issue.

**Comment by just4t** [comment]
@JoshData [Done!](https://github.com/mail-in-a-box/mailinabox/issues/1437#issue-367582313)
