### ISSUE TITLE
lmtp error - read-only filesystem

### ISSUE THREAD

**Issue by jalogisch** [mail-in-a-box/mailinabox#1571]
quite regular I notice the following error message in the `mail.log` I do not miss any message and it is stored - but I can't see a reason for this kind of message. 

The references I can find in the dovecot ml are quite old (2014) and do not give a guidance to fix.

```
Apr 29 08:04:49 lmtp(jalogisch@jalogis.ch): Error: open(/etc/dovecot/sieve-spam.svbin.box.jalogis.ch.557.cbbce94f0bc08cdb) failed: Read-only file system
Apr 29 08:04:49 lmtp(jalogisch@jalogis.ch): Error: uFrjE/+TxlwtAgAA9QknEw: sieve: binary save: failed to create temporary file: open(/etc/dovecot/sieve-spam.svbin.) failed: Read-only file system
Apr 29 08:04:49 lmtp(jalogisch@jalogis.ch): Info: uFrjE/+TxlwtAgAA9QknEw: sieve: msgid=<0100016a67adb2f0-838c2ea4-bd09-4531-aba8-fb86ff3d026d-000000@email.amazonses.com>: stored mail into mailbox 'INBOX'
Apr 29 08:04:49 box postfix/lmtp[32637]: 1EF8E5DF72: to=<jalogisch@jalogis.ch>, relay=127.0.0.1[127.0.0.1]:10025, delay=4.1, delays=1.4/0/0.02/2.7, dsn=2.0.0, status=sent (250 2.0.0 <jalogisch@jalogis.ch> uFrjE/+TxlwtAgAA9QknEw Saved)
Apr 29 08:04:49 lmtp(557): Info: Disconnect from 127.0.0.1: Successful quit
```

I run the following to check if permission are ok:

```
sievec /etc/dovecot/sieve-spam.sieve
```

what does not give any error messages. maybe someone else is able to guide or give some idea what might be the reason.

MIAB: Version 0.41 (latest at the time of writing this)

**Comment by infidelus** [comment]
Having installed Miab a couple of months ago, I've just been looking through my mail logs for a different error to report and am also seeing this lmtp error.  Version 0.44.

> May 11 04:30:17 lmtp(randomemailname@mydomain.com): Error: open(/etc/dovecot/sieve-spam.svbin.box.mydomain.com.32048.b66c4498371e18a8) failed: Read-only file system
May 11 04:30:17 lmtp(randomemailname@mydomain.com): Error: MFmNDMfGuF4wfQAArsgQwA: sieve: binary save: failed to create temporary file: open(/etc/dovecot/sieve-spam.svbin.) failed: Read-only file system
May 11 04:30:17 lmtp(randomemailname@mydomain.com): Info: MFmNDMfGuF4wfQAArsgQwA: sieve: msgid=<E1jXzAN-000720-B9@smtp-01-tuk1.steampowered.com>: stored mail into mailbox 'INBOX'
May 11 04:30:17 box postfix/lmtp[32047]: DD680A0177: to=<randomemailname@mydomain.com>, orig_to=<steam13@mydomain.com>, relay=127.0.0.1[127.0.0.1]:10025, delay=3.8, delays=1.4/0.02/0.01/2.4, dsn=2.0.0, status=sent (250 2.0.0 <randomemailname@mydomain.com> MFmNDMfGuF4wfQAArsgQwA Saved)
May 11 04:30:17 lmtp(32048): Info: Disconnect from 127.0.0.1: Successful quit

**Comment by anoma** [comment]
FWIW I cannot find a single instance of this error.

**Comment by infidelus** [comment]
On the flip side, I see it multiple times an hour on my MIAB install, which I've only been running for about 2 months.

**Comment by myfirstnameispaul** [comment]
I just fixed this problem for myself with good ol' `sudo mailinabox`.

**Comment by infidelus** [comment]
Thanks, tried that yesterday but still seeing those errors in the log regularly

**Comment by myfirstnameispaul** [comment]
Did you check your logs? IIRC, LMTP (Dovecot) handles these. Maybe there is a debug or verbose logging mode if that doesn't reveal anything.

**Comment by infidelus** [comment]
Not sure what's going on now.  Think it must be me going senile.

I ran sudo mailinabox yesterday morning and I could swear I still saw errors after, and I definitely had an error saving drafts today.

I updated to .45 earlier and I've just gone back into the mail.log to look again, and now I can't see any read-only errors after 10am yesterday and I successfully saved a draft.

Colour me confused ...

**Comment by myfirstnameispaul** [comment]
Try moving mails to different different directories. That usually brings the error.

**Comment by infidelus** [comment]
Thanks again.  I tried moving one of my existing emails between directories but didn't get any errors.  Saving as draft is inconsistent.  I've saved a couple successfully but another couple error'd out with that file access error.

**Comment by TheCranston** [comment]
I've been facing this issue as well.  After a bit of digging I found the systemd service for dovecot is set to

`ProtectSystem=full`

which in turn according to the docs I’m reading [https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ProtectSystem= ](https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ProtectSystem= )says that setting will result in the /etc hierarchy being mounted as read only for the service. To me it feels like that’s the core issue.  I’m not sure the correct path forward.  Thoughts???
