### ISSUE TITLE
Emails going into spam/junk folders, outlook.com and gmail

### ISSUE THREAD

**Issue by stevetoza** [mail-in-a-box/mailinabox#358]
Hello, 

All the emails I send from my miab always go into outlook/hotmail and gmail spam/junk folders. DNS is running on the box and the domain is set up correctly pointing to the box,  in the status check page everything is showing as green ticked status

When using mail-tester.com to check, I see:

    A DMARC policy allows a sender to indicate that their emails are protected by SPF and/or DKIM, and       give instruction if neither of those authentication methods passes. Please be sure you have a DKIM and     SPF set before using DMARC.
    You are not allowed to send a message with this address

I have checked the headers when the email goes into the spam folder and seems to be showing that dmarc as a fail see below:

    Received: from box.domain.email ([111.111.11.111]) by BAY004-MC2F24.hotmail.com over TLS secured channel with Microsoft SMTPSVC(7.5.7601.22751);
    Fri, 20 Mar 2015 12:26:21 -0700
    Received: from authenticated-user (unknown [127.0.0.1])
    (using TLSv1 with cipher ECDHE-RSA-AES256-SHA (256/256 bits))
    (No client certificate requested)
    by box.domain.email (Postfix) with ESMTPSA id 2063830164B
    for <emailaddress@outlook.com>; Fri, 20 Mar 2015 15:22:07 -0400 (EDT)
    Authentication-Results: box; dmarc=fail header.from=domain.email
    DKIM-Signature: v=1; a=rsa-sha256; c=simple/simple; d=fuzmo.email; s=mail;
    t=1426879328; bh=sBAGiNV4KYLbm0g/+Uk7wkytoprDH+f2JKFDxmiA7hE=;
    h=Date:From:To:Subject:From;
    b=TD80CzAK8gy22HAwyd4mlpmNRuPLwiZGTlZM7Rtc3Pd3bZ3ye4EajGExgTKcswCh8
    sc3BfwAOoEhQvPpBHSYP+f4CANgpTAJuePKoDAvsvKOgJk3tS4VcjQ6ca7IIjn6aXb
    U3tYF4J7eSekZaFpQL2g+eRKgMSILXRFXBdv0bHg=

**Comment by JoshData** [comment]
Would you send me an email at jt@occams.info so I can see what the headers look like in an actual email? I'll post here anything I figure out.

**Comment by JoshData** [comment]
So it actually appears correct to me:

Headers set on receipt by my box:

	Authentication-Results: box.occams.info; dmarc=pass header.from=fuzmo.email
	Authentication-Results: box.occams.info; dkim=pass ... header.d=fuzmo.email header.i=@fuzmo.email ...
	Received: from box.fuzmo.email .... by box.occams.info ....

Headers added by your box:

	Received: from authenticated-user (unknown [127.0.0.1]) .... box.fuzmo.email
	Authentication-Results: box; dmarc=fail header.from=fuzmo.email
	DKIM-Signature: ... d=fuzmo.email ...

Except that your box is adding a DMARC failed header on outbound mail. I see mine does this too. I don't know if this is the cause of mail being marked as junk on receipt, but this is something that I need to fix.

**Comment by stevetoza** [comment]
I see, 

is that causing www.mail-tester.com to show 

    A DMARC policy allows a sender to indicate that their emails are protected by SPF and/or DKIM, and     give instruction if neither of those authentication methods passes. Please be sure you have a DKIM and SPF set before using DMARC.
You are not allowed to send a message with this address

You can check the results by going to 

http://www.mail-tester.com/web-BpwQWb

**Comment by JoshData** [comment]
Maybe.

I just committed a fix to not put this header on outbound mail. If you can update to the latest on github (then run `mailinabox`) and let me know if a) the header disappears and b) mail-tester gives an OK, that'd be a big help. Thanks!

**Comment by stevetoza** [comment]
Hello, 

Headers still show as dmarc=fail

    Authentication-Results: box; dmarc=fail header.from=fuzmo.email

mail-tester.com the same 

Cheers

**Comment by stevetoza** [comment]
Hi Josh, 

Looks like when I cloned the repo it didn't clone correctly. Just cloned it again and ran mailinabox and the headers are now removed but still going into spam, mail-tester.com passes all tests with DMARC policy now.

    Received: from authenticated-user (unknown [127.0.0.1])
	(using TLSv1 with cipher ECDHE-RSA-AES256-SHA (256/256 bits))
	(No client certificate requested)
	by box.fuzmo.email (Postfix) with ESMTPSA id 8D12C1A0823

I did notice something else when I ran mailinabox command:

    root@box:~/mailinabox/management# mailinabox

    Running migration to Mail-in-a-Box #4...
    Error: duplicate column name: privileges

    Error running the migration script:

    Command '['sqlite3', '/home/user-data/mail/users.sqlite', "ALTER TABLE users ADD privileges TEXT        NOT NULL DEFAULT ''"]' returned non-zero exit status 1

    Your system may be in an inconsistent state now. We're terribly sorry. A re-install from a backup might     be the best way to continue.

**Comment by JoshData** [comment]
> Running migration to Mail-in-a-Box #4...

That's odd. If you run `mailinabox` again, does it do it again or is it ok?

**Comment by hnk** [comment]
Applying only the fix in dcd971d079339f10b8e72b24372b47cd38a48bbc fixes the issue and www.mail-tester.com gives ma 10/10 points again, after having 06/10 because of failed DMARC tests.

I think this is closed upon the next proper release.

**Comment by JoshData** [comment]
Okay great, thanks. If you see anything else on the migration issue, feel free to open a separate issue.

**Comment by hnk** [comment]
I actually did not run this from the master branch, I manually changed the appropriate file to only fix the DKIM issue. So I cannot speak about the migration issue!

**Comment by JoshData** [comment]
Ooops. If @stevetoza sees any more migration problems!

**Comment by hnk** [comment]
But that seems to be a different issue altogether ;)

**Comment by JoshData** [comment]
That's why I'm closing this issue.

**Comment by stevetoza** [comment]
Hey sorry, no futher issues seen when migrating. Will test again if you like

**Comment by hnk** [comment]
Sorry for the comment spam, I thought you had re-opened it.
