### ISSUE TITLE
pyzor discover fails because Sourceforge is offline

### ISSUE THREAD

**Issue by anoma** [mail-in-a-box/mailinabox#496]
0.11 > 0.12b

already installed: spampd (2.30-22.2), razor (1:2.85-4build2), pyzor (1:0.5.0-2fakesync1), dovecot-antispam (2.0+20130822-2build1)

FAILED: pyzor discover
-----------------------------------------
downloading servers from http://pyzor.sourceforge.net/cgi-bin/inform-servers-0-3-x
Traceback (most recent call last):
  File "/usr/bin/pyzor", line 8, in <module>
    pyzor.client.run()
  File "/usr/lib/pymodules/python2.7/pyzor/client.py", line 1022, in run
    ExecCall().run()
  File "/usr/lib/pymodules/python2.7/pyzor/client.py", line 186, in run
    download(config.get('client', 'DiscoverServersURL'), servers_fn)
  File "/usr/lib/pymodules/python2.7/pyzor/client.py", line 1031, in download
    open(outfile, "wb").write(urllib2.urlopen(url).read())
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Unavailable
-----------------------------------------

If you follow http://pyzor.sourceforge.net/cgi-bin/inform-servers-0-3-x in a normal browser you see a message from sourceforge:

 The sourceforge.net website is temporarily in static offline mode.
Only a very limited set of project pages are available until the main website returns to service.

No one should trust sourceforge anymore anyway due to their recent unethical behavior and the high likely hood they will fall of the internet at any moment

**Comment by dhpiggott** [comment]
I ran into this just now too, as I was going to be migrating my box from one VPS to another this morning... it'll have to wait now!

The reference to Sourceforge seems to be a property of Pyzor itself - its not set by MIAB. So I see three possible actions for this issue:

1. Do nothing (close this - the workaround is to just wait for Sourceforge to return and/or for Pyzor to be updated with a new server bootstrap location).
2. See if Pyzor's configuration can be overriden to use some alternative server bootstrap location.
3. Drop Pyzor(!?).

(1) would seem most pragmatic to me, even though this is annoying.

**Comment by dhpiggott** [comment]
Nice. Unfortunately it fails for me - both on my existing box and on the one I'm attempting to get setup ready for migration:
`setup/spamassassin.sh: line 35: /etc/spamassassin/pyzor/servers: No such file or directory`.

(I checked and neither box has a `/etc/spamassassin/pyzor` directory).

FWIW (it's related in that it's due to SourceForge failure): my deployment will still have to wait because the Roundcube download fails with a checksum mismatch:
```
installing Roundcube webmail 1.1.2...
sha1sum: WARNING: 1 computed checksum did NOT match
------------------------------------------------------------
Download of http://downloads.sourceforge.net/project/roundcubemail/roundcubemail/1.1.2/roundcubemail-1.1.2.tar.gz did not match expected checksum.
Found:
ea60df615387f47bdfdfe4da48f6567c4ec60f74  /tmp/roundcube.tgz

Expected:
df88deae691da3ecf3e9f0aee674c1f3042ea1eb  /tmp/roundcube.tgz
```

**Comment by JoshData** [comment]
Okay both issues should be fixed now. I added my own mirror of roundcube.

**Comment by JoshData** [comment]
05e33edb0d63716e5d6e4db304d45ab8e913cb46 and 40a5fa46d1ee44fd093bcfa5c94a879ca84fffa5

**Comment by bkniffler** [comment]
bootstrap.sh still doesn't seem to work, has it been updated? Thanks!

**Comment by JoshData** [comment]
No sorry just fixed in master so far.

**Comment by dhpiggott** [comment]
Thanks, setup of pyzor and Roundcube does work now.

...however:
```
installing Roundcube webmail 1.1.2...
already installed: dbconfig-common (1.8.47+nmu1), php5-cli (5.5.9+dfsg-1ubuntu4.11), php5-sqlite (5.5.9+dfsg-1ubuntu4.11), php5-gd (5.5.9+dfsg-1ubuntu4.11), php5-imap (5.4.6-0ubuntu5), php-pear (5.5.9+dfsg-1ubuntu4.11), curl (7.35.0-1ubuntu2.5), php5 (5.5.9+dfsg-1ubuntu4.11), php5-gd (5.5.9+dfsg-1ubuntu4.11), php5-fpm (5.5.9+dfsg-1ubuntu4.11), unzip (6.0-9ubuntu1.3)
installing php5-curl php-apc libapr1 libtool libcurl4-openssl-dev php-xml-parser php5-dev memcached php5-memcache ...
installing ownCloud...
creating sqlite db

FAILED: sudo -u www-data php /usr/local/lib/owncloud/occ upgrade
-----------------------------------------
ownCloud is already latest version
-----------------------------------------
```

I will investigate in due course and open a new issue if appropriate. This is a first-install that has failed and then been resumed twice, so maybe it's just an edge case of something not being entirely idempotent. Or maybe it was because I pulled master between the first and second attempts.

So if I say nothing more about this it'll be because I've concluded it's really not a bug of any sort and was essentially PEBKAC.

**Comment by dhpiggott** [comment]
Well I just ran setup a fourth time - I didn't change anything relative to the third run - and this time ownCloud setup worked just fine. I didn't dig any further, but am assuming this was a result of me resuming the initial setup failure with newer commits (the first run was pre f7298a45bd5f78dfc5f48f15255d8a35e8f3602f & 76dba1a5210c5e076d0b5da8969cd9b463600bfb, the second and all others were post f7298a45bd5f78dfc5f48f15255d8a35e8f3602f & 76dba1a5210c5e076d0b5da8969cd9b463600bfb).

**Comment by JoshData** [comment]
I think ownCloud's upgrade script is, starting in 8.1.0, returning a new non-zero exist status (3) when there is nothing to upgrade. I just committed yet another fix to not consider `ownCloud is already latest version` a failure condition. Thanks for catching that.
